### ISSUE TITLE
Vaccine availability status

### ISSUE THREAD

**Issue by Sikerdebaard** [KJ-Waller/TrashVax#1]
Here's an example of what the page looks like when there's doses available: https://beta.prullenbakvaccin.nl/

![image](https://user-images.githubusercontent.com/801853/118538837-fc1ca580-b74e-11eb-8610-540123dd4dc3.png)

**Comment by KJ-Waller** [comment]
Thank you so much! I'm a little busy today, I'll probably have a look at it later tonight. This would be perfect to properly test out the app and make it a bit more stable.

I'll close the issue when I've made some changes.

**Comment by KJ-Waller** [comment]
Took a bit longer than expected, but it's fixed now. Thanks for your help
